# Generated by Django 3.2 on 2021-12-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='lang',
            field=models.CharField(choices=[(None, 'Выберите язык'), ('Ru', 'Русский'), ('Kg', 'Кыргызский')], default=None, max_length=40, verbose_name='Язык вопроса-ответа'),
        ),
    ]
