# Generated by Django 3.2 on 2021-12-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=40, null=True, verbose_name='Язык вопроса-ответа'),
        ),
    ]
