# Generated by Django 3.2 on 2021-10-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(upload_to='news'),
        ),
    ]
