# Generated by Django 3.2.7 on 2021-10-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211001_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='impotant',
            field=models.BooleanField(default=False, verbose_name='Важная новость'),
        ),
    ]
