# Generated by Django 3.2 on 2021-10-26 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_alter_news_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='banners',
            field=models.BooleanField(default=False, verbose_name='Поставить обложку в баннер'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='Обложка новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Отрывок из статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='language',
            field=models.CharField(choices=[(None, 'Выберите язык'), ('Ru', 'Русский'), ('Kg', 'Кыргызский'), ('En', 'Английский')], default='Ru', max_length=15, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
