# Generated by Django 3.2 on 2022-03-17 19:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
