# Generated by Django 3.2 on 2021-12-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Заголовок'),
        ),
    ]
