# Generated by Django 3.2 on 2021-12-15 08:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(db_index=True, verbose_name='Текст страницы'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='title',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Заголовок'),
        ),
    ]
