# Generated by Django 3.2 on 2022-03-17 19:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('На русском', (('Math_ru', 'Математика'), ('Analogies_ru', 'Аналогии и дополнения предложений'), ('Reading_ru', 'Чтение и понимание'), ('Grammatic_practice_ru', 'Практическая грамматика русского языка'), ('History_ru', 'История'), ('Physics_ru', 'Физика'), ('Biology_ru', 'Биология'), ('Chemistry_ru', 'Химия'), ('Math_subj_ru', 'Математика предметная'), ('English_ru', 'Английский язык'))), ('Кыргызча', (('Math_kg', 'Математика'), ('Analogies_kg', 'Окшоштуктар жана сүйлөмдөрдү толуктоо'), ('Reading_kg', 'Текстти окуу жана түшүнүү'), ('Grammatic_practice_kg', 'Кыргыз тилинин практикалык грамматикасы'), ('History_kg', 'Тарых'), ('Physics_kg', 'Физика'), ('Biology_kg', 'Биология'), ('Chemistry_kg', 'Химия'), ('Math_subj_kg', 'Математика предметная'), ('English_kg', 'Англис тили')))], db_index=True, max_length=100, verbose_name='Предмет')),
                ('part_num', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X')], null=True, verbose_name='Часть')),
                ('version', models.IntegerField(default=1, verbose_name='Вариант')),
                ('duration', models.IntegerField(verbose_name='Время (в минутах)')),
                ('num_questions', models.IntegerField(verbose_name='Количество вопросов')),
                ('num_answers', models.IntegerField(verbose_name='Количество вариантов ответа')),
                ('lang', models.CharField(choices=[(None, 'Выберите язык'), ('Ru', 'Русский'), ('Kg', 'Кыргызский'), ('En', 'Английский')], default='Ru', max_length=15, verbose_name='Язык теста')),
                ('eng_test', models.BooleanField(default=False, help_text='Включить только для теста по английскому языку', verbose_name='Тест по английскому языку')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('intro', ckeditor.fields.RichTextField(verbose_name='Приветственный текст')),
            ],
            options={
                'verbose_name': 'Онлайн тест',
                'verbose_name_plural': 'Онлайн тесты',
            },
        ),
        migrations.CreateModel(
            name='OnlineTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ImageField(upload_to='ort/images/question/', verbose_name='Картинка с вопросами')),
                ('num_start', models.IntegerField(verbose_name='С какого вопроса начинается тест на картинке(номер)')),
                ('num_end', models.IntegerField(verbose_name='На каком вопросе заканчивается тест на картинке(номер)')),
                ('onlinetest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='online_test.onlinetest')),
            ],
            options={
                'verbose_name': 'Вопрос к тесту',
                'verbose_name_plural': 'Вопросы к тесту',
            },
        ),
        migrations.CreateModel(
            name='AnswerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, verbose_name='Номер вопроса')),
                ('correct_answer', models.CharField(blank=True, choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е')], default='А', max_length=2, verbose_name='Правильный ответ')),
                ('onlinetest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='online_test.onlinetest')),
            ],
            options={
                'verbose_name': 'Ответ к тесту',
                'verbose_name_plural': 'Ответы к тесту',
            },
        ),
    ]
