# Generated by Django 3.2.7 on 2021-11-04 16:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Предмет')),
                ('part_num', models.IntegerField(default=1, verbose_name='Часть')),
                ('version', models.IntegerField(default=1, verbose_name='Вариант')),
                ('duration', models.IntegerField(verbose_name='Время (в минутах)')),
                ('num_questions', models.IntegerField(verbose_name='Количество вопросов')),
                ('num_answers', models.IntegerField(verbose_name='Количество вариантов ответа')),
                ('language', models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский'), ('En', 'Английский')], default='Ru', max_length=15, verbose_name='Язык теста')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('intro', ckeditor.fields.RichTextField(verbose_name='Приветственный текст')),
            ],
            options={
                'verbose_name': 'Онлайн тест',
                'verbose_name_plural': 'Онлайн тесты',
            },
        ),
        migrations.CreateModel(
            name='OnlineTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ImageField(upload_to='ort/images/question/', verbose_name='Картинка с вопросами')),
                ('num_start', models.IntegerField(verbose_name='С какого вопроса начинается тест на картинке(номер)')),
                ('num_end', models.IntegerField(verbose_name='На каком вопросе заканчивается тест на картинке(номер)')),
                ('onlinetest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='online_test.onlinetest')),
            ],
            options={
                'verbose_name': 'вопрос к тесту',
                'verbose_name_plural': 'Вопросы к тесту',
            },
        ),
        migrations.CreateModel(
            name='AnswerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса')),
                ('correct_answer', models.IntegerField(choices=[(1, 'А'), (2, 'Б'), (3, 'В'), (4, 'Г'), (5, 'Д'), (6, 'Е')], default=1, verbose_name='Правильный ответ')),
                ('onlinetest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='online_test.onlinetest')),
            ],
            options={
                'verbose_name': 'Ответ к тесту',
                'verbose_name_plural': 'Ответы к тесту',
            },
        ),
    ]
