# Generated by Django 3.2 on 2021-10-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetest',
            name='name',
            field=models.CharField(choices=[('Math_ru', 'Математика'), ('Math_kg', 'Математика'), ('Analogies_ru', 'Аналогии и дополнения предложений'), ('Analogies_kg', 'Аналогии и дополнения предложений'), ('Reading_ru', 'Чтение и понимание'), ('Reading_kg', 'Чтение и понимание'), ('Grammatic_practice_ru', 'Практическая грамматика русского языка'), ('Grammatic_practice_kg', 'Практическая грамматика кыргызского языка'), ('History_ru', 'История'), ('History_kg', 'История'), ('Physics_ru', 'Физика'), ('Physics_kg', 'Физика'), ('Biology_ru', 'Биология'), ('Biology_kg', 'Биология'), ('Chemistry_ru', 'Химия'), ('Chemistry_kg', 'Химия'), ('Math_subj_ru', 'Математика предметная'), ('Math_subj_kg', 'Математика предметная')], max_length=50, verbose_name='Предмет'),
        ),
    ]
