# Generated by Django 3.2.7 on 2021-10-13 14:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Предмет')),
                ('part_num', models.IntegerField(default=1, verbose_name='Часть')),
                ('version', models.IntegerField(default=1, verbose_name='Вариант')),
                ('duration', models.IntegerField(verbose_name='Время (в минутах)')),
                ('num_questions', models.IntegerField(verbose_name='Количество заданий')),
                ('num_answers', models.IntegerField(verbose_name='Количество вариантов ответа')),
                ('language', models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский'), ('En', 'Английский')], default='Ru', max_length=15, verbose_name='Язык теста')),
                ('is_active', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('intro', ckeditor.fields.RichTextField(verbose_name='Приветственный текст')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='category',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
    ]
