# Generated by Django 3.2 on 2021-11-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertest',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е')], default='А', max_length=2, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='answertest',
            name='question_number',
            field=models.IntegerField(blank=True, verbose_name='Номер вопроса'),
        ),
    ]
