# Generated by Django 3.2 on 2024-11-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetest',
            name='lang',
            field=models.CharField(choices=[(None, 'Выберите язык'), ('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15, verbose_name='Язык теста'),
        ),
    ]
