# Generated by Django 3.2 on 2021-12-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetest',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Предмет'),
        ),
    ]
