# Generated by Django 3.2 on 2021-10-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answertest',
            options={'verbose_name': 'Ответ к тесту', 'verbose_name_plural': 'Ответы к тесту'},
        ),
        migrations.AlterModelOptions(
            name='onlinetestquestion',
            options={'verbose_name': 'вопрос к тесту', 'verbose_name_plural': 'Вопросы к тесту'},
        ),
    ]
