# Generated by Django 3.2 on 2024-11-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0002_alter_onlinetest_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetestquestion',
            name='question_image',
            field=models.BooleanField(default=False, verbose_name='Экран с картинкой вопроса'),
        ),
    ]
