# Generated by Django 3.2.7 on 2021-10-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0002_auto_20211013_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinetest',
            options={'verbose_name': 'Онлайн тест', 'verbose_name_plural': 'Онлайн тесты'},
        ),
    ]
