# Generated by Django 3.2 on 2024-11-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("online_test", "0003_onlinetestquestion_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinetest",
            name="order_number",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Порядковый номер"
            ),
        ),
    ]
