# Generated by Django 3.2 on 2021-10-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0003_alter_onlinetest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetest',
            name='part_num',
            field=models.CharField(blank=True, max_length=20, verbose_name='Часть'),
        ),
    ]
