# Generated by Django 3.2.7 on 2021-10-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0004_alter_onlinetest_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ImageField(upload_to='ort/images/question/', verbose_name='Картинка с вопросами')),
                ('num_start', models.IntegerField(verbose_name='С какого вопроса начинается тест на картинке(номер)')),
                ('num_end', models.IntegerField(verbose_name='На каком вопросе заканчивается тест на картинке(номер)')),
                ('onlinetest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='online_test.onlinetest')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса')),
                ('correct_answer', models.IntegerField(choices=[(1, 'А'), (2, 'Б'), (3, 'В'), (4, 'Г'), (5, 'Д'), (6, 'Е')], default=1, verbose_name='Правильный ответ')),
                ('onlinetest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='online_test.onlinetest')),
            ],
        ),
    ]
