# Generated by Django 3.2 on 2024-11-11 22:43

from django.db import migrations


def update_order_number(apps, schema_editor):
    OnlineTest = apps.get_model("online_test", "OnlineTest")
    for ind, test in enumerate(OnlineTest.objects.all(), start=1):
        test.order_number = ind
        test.save()


def reverse_update_order_number(apps, schema_editor):
    OnlineTest = apps.get_model("online_test", "OnlineTest")
    for test in OnlineTest.objects.all():
        test.order_number = 1
        test.save()


class Migration(migrations.Migration):
    dependencies = [
        ("online_test", "0004_auto_20241112_0442"),
    ]

    operations = [
        migrations.RunPython(update_order_number, reverse_update_order_number),
    ]
