# Generated by Django 3.2 on 2021-10-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0005_alter_onlinetest_part_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetest',
            name='language',
            field=models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15, verbose_name='Язык теста'),
        ),
    ]
