# Generated by Django 3.2 on 2021-10-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0006_alter_onlinetest_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetest',
            name='part_num',
            field=models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X')], max_length=20, verbose_name='Часть'),
        ),
    ]
