# Generated by Django 3.2.7 on 2021-11-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('link', models.URLField()),
                ('lang_footer_link', models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский'), ('En', 'Английский')], default='Ru', max_length=15)),
            ],
            options={
                'verbose_name': 'Ссылка футера',
                'verbose_name_plural': 'Ссылки футера',
            },
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('link', models.URLField()),
                ('icon', models.ImageField(help_text='Добавлять только картинки размера 25х25', unique=True, upload_to='media/icons_menu')),
                ('lang_menu_link', models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский'), ('En', 'Английский')], default='Ru', max_length=15)),
            ],
            options={
                'verbose_name': 'Ссылка в меню',
                'verbose_name_plural': 'Ссылки меню',
            },
        ),
    ]
