# Generated by Django 3.2 on 2021-12-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('link', models.URLField()),
                ('lang', models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15)),
            ],
            options={
                'verbose_name': 'Ссылка футера',
                'verbose_name_plural': 'Ссылки футера',
            },
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('icon', models.FileField(blank=True, help_text='Добавлять только картинки размера 25х25', null=True, unique=True, upload_to='icons_menu', verbose_name='Иконка')),
                ('lang', models.CharField(blank=True, choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15, null=True, verbose_name='Язык')),
                ('position', models.CharField(blank=True, choices=[('left', 'Левое меню'), ('bottom', 'Нижнее меню')], default='left', help_text='Укажите в каком меню появится эта ссылка. В левом боковом или нижнем среднем', max_length=10, null=True, verbose_name='Позиция меню')),
                ('page', models.ForeignKey(blank=True, help_text='Укажите страницу, если ссылка должна указывать на неё', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='page_link', to='pages.page', verbose_name='Связанная страница')),
            ],
            options={
                'verbose_name': 'Ссылка в меню',
                'verbose_name_plural': 'Ссылки меню',
            },
        ),
    ]
