# Generated by Django 3.2 on 2022-02-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('link', models.URLField()),
                ('lang', models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15)),
            ],
            options={
                'verbose_name': 'Ссылка футера',
                'verbose_name_plural': 'Ссылки футера',
            },
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('icon', models.CharField(blank=True, choices=[('<i class="fas fa-bookmark"></i>', 'ОРТ'), ('<i class="fas fa-copy"></i>', 'Школьная Олимпиада'), ('<i class="fas fa-graduation-cap"></i>', 'Абитуриентам'), ('<i class="fas fa-chalkboard-teacher"></i>', 'Учителям')], max_length=50, null=True, verbose_name='Иконка')),
                ('lang', models.CharField(blank=True, choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15, null=True, verbose_name='Язык')),
                ('link', models.CharField(blank=True, help_text='Выберите что-то одно, либо связанную страницу, либо ссылку в это поле', max_length=300, null=True, verbose_name='Ссылка на другие сайты или страницы этого сайта')),
                ('position', models.CharField(blank=True, choices=[('left', 'Левое меню'), ('bottom', 'Нижнее меню'), ('banner', 'На баннере')], default='left', help_text='Укажите в каком меню появится эта ссылка. В левом боковом, на баннере или нижнем среднем', max_length=10, null=True, verbose_name='Позиция меню')),
                ('page', models.ForeignKey(blank=True, help_text='Укажите страницу, если ссылка должна указывать на неё', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='page_link', to='pages.page', verbose_name='Связанная страница')),
            ],
            options={
                'verbose_name': 'Ссылка в меню',
                'verbose_name_plural': 'Ссылки меню',
            },
        ),
    ]
