# Generated by Django 3.2 on 2021-11-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='icon',
            field=models.ImageField(help_text='Добавлять только картинки размера 25х25', unique=True, upload_to='icons_menu'),
        ),
    ]
