# Generated by Django 3.2 on 2021-10-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='lang_footer_link',
            field=models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='lang_menu_link',
            field=models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15),
        ),
    ]
