# Generated by Django 3.2.7 on 2021-10-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20211008_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterObject',
            new_name='FooterLink',
        ),
        migrations.RenameModel(
            old_name='MenuObject',
            new_name='MenuLink',
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': 'Ссылка футера', 'verbose_name_plural': 'Ссылки футера'},
        ),
        migrations.AlterModelOptions(
            name='menulink',
            options={'verbose_name': 'Ссылка в меню', 'verbose_name_plural': 'Ссылки меню'},
        ),
        migrations.RenameField(
            model_name='footerlink',
            old_name='lang_footer_object',
            new_name='lang_footer_link',
        ),
        migrations.RenameField(
            model_name='menulink',
            old_name='lang_menu_object',
            new_name='lang_menu_link',
        ),
    ]
