# Generated by Django 3.2 on 2021-12-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20211210_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='icon',
            field=models.CharField(blank=True, choices=[('<i class="fas fa-bookmark"></i>', 'ОРТ'), ('<i class="fas fa-copy"></i>', 'Школьная Олимпиада'), ('<i class="fas fa-graduation-cap"></i>', 'Абитуриентам'), ('<i class="fas fa-chalkboard-teacher"></i>', 'Учителям')], max_length=50, null=True, verbose_name='Иконка'),
        ),
    ]
