# Generated by Django 3.2 on 2021-10-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(unique=True)),
                ('lang_course', models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский'), ('En', 'Английский')], default='Ru', max_length=15)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('video_link', models.URLField(blank=True, max_length=150, unique=True)),
                ('lang_video', models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский'), ('En', 'Английский')], default='Ru', max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videocourses.course')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
