# Generated by Django 3.2 on 2021-12-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lang',
            field=models.CharField(choices=[(None, 'Выберите язык'), ('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15, verbose_name='Язык курса'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lang',
            field=models.CharField(choices=[(None, 'Выберите язык'), ('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15, verbose_name='Язык видео'),
        ),
    ]
