# Generated by Django 3.2 on 2021-10-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lang_course',
            field=models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15, verbose_name='Язык курса'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lang_video',
            field=models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский')], default='Ru', max_length=15, verbose_name='Язык видео'),
        ),
    ]
