# Generated by Django 3.2.7 on 2021-10-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(unique=True, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lang_course',
            field=models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский'), ('En', 'Английский')], default='Ru', max_length=15, verbose_name='Язык курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videocourses.course', verbose_name='Принадлежащий курс'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lang_video',
            field=models.CharField(choices=[('Ru', 'Русский'), ('Kg', 'Кыргызский'), ('En', 'Английский')], default='Ru', max_length=15, verbose_name='Язык видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.URLField(blank=True, max_length=150, unique=True, verbose_name='Ссылка на видео'),
        ),
    ]
