# Generated by Django 3.2 on 2021-12-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0002_auto_20211210_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название курса'),
        ),
    ]
