# Generated by Django 3.2.7 on 2021-09-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0002_rename_video_course_video_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='videocourses.course'),
        ),
    ]
