# Generated by Django 3.2.7 on 2021-09-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0003_alter_video_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
