# Generated by Django 3.2.7 on 2021-09-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0005_alter_video_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_link',
        ),
    ]
