# Generated by Django 3.2.7 on 2021-09-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0006_remove_video_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_link',
            field=models.URLField(blank=True, max_length=150, unique=True),
        ),
    ]
