# Generated by Django 3.2.7 on 2021-09-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0007_video_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='video_name',
        ),
    ]
