# Generated by Django 3.2.7 on 2021-09-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0008_auto_20210924_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_name',
            new_name='name',
        ),
    ]
