# Generated by Django 3.2.7 on 2021-09-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0009_auto_20210924_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videocourses.course'),
        ),
    ]
