# Generated by Django 3.2.7 on 2021-09-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0010_alter_video_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='course_id',
            new_name='course',
        ),
    ]
